version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands: 
      - echo `PORT=${PORT}` >> .env

      - echo "CLIENT_ID=$(aws --region=us-east-1 ssm get-parameter --name "CLIENT_ID" --with-decryption --output text --query Parameter.Value)" >> .env
      - echo "CLIENT_SECRET=$(aws --region=us-east-1 ssm get-parameter --name "CLIENT_SECRET" --with-decryption --output text --query Parameter.Value)" >> .env
      - echo `REDIRECT_URI=${REDIRECT_URI}` >> .env

      - echo `AUTH_URL=${AUTH_URL}` >> .env
      - echo `TOKEN_URL=${TOKEN_URL}` >> .env
      - echo `API_BASE_URL=${API_BASE_URL}` >> .env

      - echo "LASTFM_API_KEY=$(aws --region=us-east-1 ssm get-parameter --name "LASTFM_API_KEY" --with-decryption --output text --query Parameter.Value)" >> .env
      - echo "LASTFM_SHARED_SECRET=$(aws --region=us-east-1 ssm get-parameter --name "LASTFM_SHARED_SECRET" --with-decryption --output text --query Parameter.Value)" >> .env
      - echo `LASTFM_API_BASE_URL=${LASTFM_API_BASE_URL}` >> .env
      
artifacts:
  files:
    - '**/*'